name: ShellCheck

on:
  push:
    branches: [main]
  pull_request:

jobs:
  shellcheck:
    name: Analizar scripts de Bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ./scripts
          severity: warning
